
$(function() {
    $('form input').click(function() {

    $('#myModal').modal('hide');
     var chosenLeague = $('form input:checked').val();
     document.getElementById("leagueNow").innerHTML = chosenLeague;

    });
});

function filterTeams(league, chosenLeague) {
    if (chosenLeague === "All leagues") {
        return league;
    }

    return _.filter(league, function(team) {
        return team.league === chosenLeague;
    });
}

function randomLeague() {
    var array = document.getElementsByName('league');
    var randomNumber = Math.floor(Math.random() * 36);

    array[randomNumber].checked = true;
}

function chooseFunctio() {

    var chosenLeague = $('form input:checked').val();

    var leagueTeam = filterTeams(league, chosenLeague);

    var teams = _.sample(leagueTeam, 2);

    document.getElementById("team1").innerHTML = teams[0].league + " <br> " + teams[0].team;
    document.getElementById("team2").innerHTML = teams[1].league + " <br> " + teams[1].team;
   
}
//http://www.easports.com/fifa/news-updates-gameplay/article/fifa-14-leagues
var league = [
    //Mexico Liga MX
    {"league": "Mexico Liga MX", "team": "América"},
    {"league": "Mexico Liga MX", "team": "Atlante"},
    {"league": "Mexico Liga MX", "team": "Atlas"},
    {"league": "Mexico Liga MX", "team": "Chiapas"},
    {"league": "Mexico Liga MX", "team": "Club León"},
    {"league": "Mexico Liga MX", "team": "Cruz Azul"},
    {"league": "Mexico Liga MX", "team": "Guadalajara"},
    {"league": "Mexico Liga MX", "team": "Monarcas"},
    {"league": "Mexico Liga MX", "team": "Monterrey"},
    {"league": "Mexico Liga MX", "team": "Pachuca"},
    {"league": "Mexico Liga MX", "team": "Puebla"},
    {"league": "Mexico Liga MX", "team": "Querétaro"},
    {"league": "Mexico Liga MX", "team": "Santos Laguna"},
    {"league": "Mexico Liga MX", "team": "Tigres"},
    {"league": "Mexico Liga MX", "team": "Tijuana"},
    {"league": "Mexico Liga MX", "team": "Toluca"},
    {"league": "Mexico Liga MX", "team": "TR Veracruz"},
    {"league": "Mexico Liga MX", "team": "U.N.A.M."},
    //USA Major League Soccer
    {"league": "USA Major League Soccer", "team": "Chicago Fire"},
    {"league": "USA Major League Soccer", "team": "Chivas USA"},
    {"league": "USA Major League Soccer", "team": "Colorado Rapids"},
    {"league": "USA Major League Soccer", "team": "Columbus Crew"},
    {"league": "USA Major League Soccer", "team": "D.C. United"},
    {"league": "USA Major League Soccer", "team": "FC Dallas"},
    {"league": "USA Major League Soccer", "team": "Houston Dynamo"},
    {"league": "USA Major League Soccer", "team": "L.A. Galaxy"},
    {"league": "USA Major League Soccer", "team": "Montreal Impact"},
    {"league": "USA Major League Soccer", "team": "New England"},
    {"league": "USA Major League Soccer", "team": "NY Red Bulls"},
    {"league": "USA Major League Soccer", "team": "Philadelphia"},
    {"league": "USA Major League Soccer", "team": "Portland"},
    {"league": "USA Major League Soccer", "team": "Real Salt Lake"},
    {"league": "USA Major League Soccer", "team": "SJ Earthquakes"},
    {"league": "USA Major League Soccer", "team": "Sounders FC"},
    {"league": "USA Major League Soccer", "team": "Sporting KC"},
    {"league": "USA Major League Soccer", "team": "Toronto FC"},
    {"league": "USA Major League Soccer", "team": "Whitecaps FC"},
    //Liga Argentina
    {"league": "Liga Argentina", "team": "All Boys"},
    {"league": "Liga Argentina", "team": "Argentinos Jrs"},
    {"league": "Liga Argentina", "team": "Arsenal"},
    {"league": "Liga Argentina", "team": "Atlético Rafaela"},
    {"league": "Liga Argentina", "team": "Belgrano"},
    {"league": "Liga Argentina", "team": "Boca Juniors"},
    {"league": "Liga Argentina", "team": "Colón"},
    {"league": "Liga Argentina", "team": "Estudiantes"},
    {"league": "Liga Argentina", "team": "Gimnasia"},
    {"league": "Liga Argentina", "team": "Godoy Cruz"},
    {"league": "Liga Argentina", "team": "Lanús"},
    {"league": "Liga Argentina", "team": "Newell's"},
    {"league": "Liga Argentina", "team": "Olimpo"},
    {"league": "Liga Argentina", "team": "Quilmes"},
    {"league": "Liga Argentina", "team": "Racing Club"},
    {"league": "Liga Argentina", "team": "River Plate"},
    {"league": "Liga Argentina", "team": "Rosario Ctral. "},
    {"league": "Liga Argentina", "team": "San Lorenzo"},
    {"league": "Liga Argentina", "team": "Tigre"},
    {"league": "Liga Argentina", "team": "Vélez Sarsfield"},
    //Liga do Brasil
    {"league": "Liga do Brasil", "team": "Atl. Mineiro"},
    {"league": "Liga do Brasil", "team": "Atl. Paranaense"},
    {"league": "Liga do Brasil", "team": "Bahia"},
    {"league": "Liga do Brasil", "team": "Botafogo"},
    {"league": "Liga do Brasil", "team": "Corinthians"},
    {"league": "Liga do Brasil", "team": "Coritiba"},
    {"league": "Liga do Brasil", "team": "Criciúma"},
    {"league": "Liga do Brasil", "team": "Cruzeiro"},
    {"league": "Liga do Brasil", "team": "Flamengo"},
    {"league": "Liga do Brasil", "team": "Fluminense"},
    {"league": "Liga do Brasil", "team": "Goiás"},
    {"league": "Liga do Brasil", "team": "Grêmio"},
    {"league": "Liga do Brasil", "team": "Internacional"},
    {"league": "Liga do Brasil", "team": "Náutico"},
    {"league": "Liga do Brasil", "team": "Ponte Preta"},
    {"league": "Liga do Brasil", "team": "Portuguesa"},
    {"league": "Liga do Brasil", "team": "Santos"},
    {"league": "Liga do Brasil", "team": "São Paulo"},
    {"league": "Liga do Brasil", "team": "Vasco da Gama"},
    {"league": "Liga do Brasil", "team": "Vitória"},
    //Campeonato Nacional Petrobras
    {"league": "Campeonato Nacional Petrobras", "team": "Audax Italiano"},
    {"league": "Campeonato Nacional Petrobras", "team": "CD Antofagasta"},
    {"league": "Campeonato Nacional Petrobras", "team": "CD Cobreloa"},
    {"league": "Campeonato Nacional Petrobras", "team": "CD Cobresal"},
    {"league": "Campeonato Nacional Petrobras", "team": "CD Everton"},
    {"league": "Campeonato Nacional Petrobras", "team": "CD Huachipato"},
    {"league": "Campeonato Nacional Petrobras", "team": "CD O'Higgins"},
    {"league": "Campeonato Nacional Petrobras", "team": "CD Palestino"},
    {"league": "Campeonato Nacional Petrobras", "team": "Colo-Colo"},
    {"league": "Campeonato Nacional Petrobras", "team": "Uni. Concepción"},
    {"league": "Campeonato Nacional Petrobras", "team": "Depor. Iquique"},
    {"league": "Campeonato Nacional Petrobras", "team": "Ñublense"},
    {"league": "Campeonato Nacional Petrobras", "team": "Rangers Talca"},
    {"league": "Campeonato Nacional Petrobras", "team": "Uni. Católica"},
    {"league": "Campeonato Nacional Petrobras", "team": "Uni. de Chile"},
    {"league": "Campeonato Nacional Petrobras", "team": "Unión Española"},
    {"league": "Campeonato Nacional Petrobras", "team": "Unión La Calera"},
    {"league": "Campeonato Nacional Petrobras", "team": "Wanderers"},
    //Colombia Liga Postobón
    {"league": "Colombia Liga Postobón", "team": "Al. Petrolera"},
    {"league": "Colombia Liga Postobón", "team": "Atl. Nacional"},
    {"league": "Colombia Liga Postobón", "team": "Atlético Huila"},
    {"league": "Colombia Liga Postobón", "team": "Boyacá Chicó"},
    {"league": "Colombia Liga Postobón", "team": "Cúcuta Depor"},
    {"league": "Colombia Liga Postobón", "team": "Depor. Quindío"},
    {"league": "Colombia Liga Postobón", "team": "Deportes Tolima"},
    {"league": "Colombia Liga Postobón", "team": "Deportivo Cali"},
    {"league": "Colombia Liga Postobón", "team": "Deportivo Pasto"},
    {"league": "Colombia Liga Postobón", "team": "Envigado"},
    {"league": "Colombia Liga Postobón", "team": "Ind. Santa Fe"},
    {"league": "Colombia Liga Postobón", "team": "Indep. Medellín"},
    {"league": "Colombia Liga Postobón", "team": "Itagüí"},
    {"league": "Colombia Liga Postobón", "team": "Junior FC"},
    {"league": "Colombia Liga Postobón", "team": "La Equidad"},
    {"league": "Colombia Liga Postobón", "team": "Millonarios FC"},
    {"league": "Colombia Liga Postobón", "team": "Once Caldas"},
    {"league": "Colombia Liga Postobón", "team": "Patriotas FC"},
    //Austrian Bundesliga
    {"league": "Austrian Bundesliga", "team": "Admira"},
    {"league": "Austrian Bundesliga", "team": "FK Austria"},
    {"league": "Austrian Bundesliga", "team": "Innsbruck"},
    {"league": "Austrian Bundesliga", "team": "RB Salzburg"},
    {"league": "Austrian Bundesliga", "team": "SK Rapid Wien"},
    {"league": "Austrian Bundesliga", "team": "SK Sturm Graz"},
    {"league": "Austrian Bundesliga", "team": "SV Grödig"},
    {"league": "Austrian Bundesliga", "team": "SV Ried"},
    {"league": "Austrian Bundesliga", "team": "Wiener Neustadt"},
    {"league": "Austrian Bundesliga", "team": "Wolfsberger AC"},
    //Belgium Pro League
    {"league": "Belgium Pro League", "team": "Cercle Brugge"},
    {"league": "Belgium Pro League", "team": "Club Brugge"},
    {"league": "Belgium Pro League", "team": "KAA Gent"},
    {"league": "Belgium Pro League", "team": "KRC Genk"},
    {"league": "Belgium Pro League", "team": "KV Kortrijk"},
    {"league": "Belgium Pro League", "team": "KV Mechelen"},
    {"league": "Belgium Pro League", "team": "KV Oostende"},
    {"league": "Belgium Pro League", "team": "Lierse SK"},
    {"league": "Belgium Pro League", "team": "OHL"},
    {"league": "Belgium Pro League", "team": "RAEC Mons"},
    {"league": "Belgium Pro League", "team": "RSC Anderlecht"},
    {"league": "Belgium Pro League", "team": "Sp. Charleroi"},
    {"league": "Belgium Pro League", "team": "Sport. Lokeren"},
    {"league": "Belgium Pro League", "team": "Standard Liège"},
    {"league": "Belgium Pro League", "team": "Waasl.-Beveren"},
    {"league": "Belgium Pro League", "team": "Zulte-Waregem"},
    //Denmark Superliga
    {"league": "Denmark Superliga", "team": "Aalborg BK"},
    {"league": "Denmark Superliga", "team": "Aarhus GF"},
    {"league": "Denmark Superliga", "team": "Brøndby IF"},
    {"league": "Denmark Superliga", "team": "Esbjerg fB"},
    {"league": "Denmark Superliga", "team": "FC København"},
    {"league": "Denmark Superliga", "team": "FC Midtjylland"},
    {"league": "Denmark Superliga", "team": "FC Nordsjælland"},
    {"league": "Denmark Superliga", "team": "FC Vestsjælland"},
    {"league": "Denmark Superliga", "team": "Odense Boldklub"},
    {"league": "Denmark Superliga", "team": "Randers FC"},
    {"league": "Denmark Superliga", "team": "SønderjyskE"},
    {"league": "Denmark Superliga", "team": "Viborg FF"},
    //England Premier League
    {"league": "England Premier League", "team": "Arsenal"},
    {"league": "England Premier League", "team": "Aston Villa"},
    {"league": "England Premier League", "team": "Cardiff City"},
    {"league": "England Premier League", "team": "Chelsea"},
    {"league": "England Premier League", "team": "Crystal Palace"},
    {"league": "England Premier League", "team": "Everton"},
    {"league": "England Premier League", "team": "Fulham"},
    {"league": "England Premier League", "team": "Hull City"},
    {"league": "England Premier League", "team": "Liverpool"},
    {"league": "England Premier League", "team": "Manchester City"},
    {"league": "England Premier League", "team": "Manchester Utd"},
    {"league": "England Premier League", "team": "Newcastle Utd"},
    {"league": "England Premier League", "team": "Norwich City"},
    {"league": "England Premier League", "team": "Southampton"},
    {"league": "England Premier League", "team": "Spurs"},
    {"league": "England Premier League", "team": "Stoke City"},
    {"league": "England Premier League", "team": "Sunderland"},
    {"league": "England Premier League", "team": "Swansea City"},
    {"league": "England Premier League", "team": "West Brom"},
    {"league": "England Premier League", "team": "West Ham"},
    //England League Championship
    {"league": "England League Championship", "team": "Barnsley"},
    {"league": "England League Championship", "team": "Birmingham City"},
    {"league": "England League Championship", "team": "Blackburn Rvrs"},
    {"league": "England League Championship", "team": "Blackpool"},
    {"league": "England League Championship", "team": "Bolton"},
    {"league": "England League Championship", "team": "Bournemouth"},
    {"league": "England League Championship", "team": "Brighton"},
    {"league": "England League Championship", "team": "Burnley"},
    {"league": "England League Championship", "team": "Charlton Ath"},
    {"league": "England League Championship", "team": "Derby County"},
    {"league": "England League Championship", "team": "Doncaster"},
    {"league": "England League Championship", "team": "Huddersfield"},
    {"league": "England League Championship", "team": "Ipswich Town"},
    {"league": "England League Championship", "team": "Leeds United"},
    {"league": "England League Championship", "team": "Leicester City"},
    {"league": "England League Championship", "team": "Middlesbrough"},
    {"league": "England League Championship", "team": "Millwall"},
    {"league": "England League Championship", "team": "Nott'm Forest"},
    {"league": "England League Championship", "team": "QPR"},
    {"league": "England League Championship", "team": "Reading"},
    {"league": "England League Championship", "team": "Sheffield Wed"},
    {"league": "England League Championship", "team": "Wigan Athletic"},
    {"league": "England League Championship", "team": "Yeovil Town"},
    //England League One
    {"league": "England League One", "team": "Bradford City"},
    {"league": "England League One", "team": "Brentford"},
    {"league": "England League One", "team": "Bristol City"},
    {"league": "England League One", "team": "Carlisle United"},
    {"league": "England League One", "team": "Colchester"},
    {"league": "England League One", "team": "Coventry City"},
    {"league": "England League One", "team": "Crawley Town"},
    {"league": "England League One", "team": "Crewe Alexandra"},
    {"league": "England League One", "team": "Gillingham"},
    {"league": "England League One", "team": "Leyton Orient"},
    {"league": "England League One", "team": "MK Dons"},
    {"league": "England League One", "team": "Notts County"},
    {"league": "England League One", "team": "Oldham Athletic"},
    {"league": "England League One", "team": "Peterborough"},
    {"league": "England League One", "team": "Port Vale"},
    {"league": "England League One", "team": "Preston"},
    {"league": "England League One", "team": "Rotherham Utd"},
    {"league": "England League One", "team": "Sheffield Utd"},
    {"league": "England League One", "team": "Shrewsbury"},
    {"league": "England League One", "team": "Stevenage"},
    {"league": "England League One", "team": "Swindon Town"},
    {"league": "England League One", "team": "Tranmere Rovers"},
    {"league": "England League One", "team": "Walsall"},
    {"league": "England League One", "team": "Wolverhampton"},
    //England League Two
    {"league": "England League Two", "team": "Accrington"},
    {"league": "England League Two", "team": "AFC Wimbledon"},
    {"league": "England League Two", "team": "Bristol Rovers"},
    {"league": "England League Two", "team": "Burton Albion"},
    {"league": "England League Two", "team": "Bury"},
    {"league": "England League Two", "team": "Cheltenham Town"},
    {"league": "England League Two", "team": "Chesterfield"},
    {"league": "England League Two", "team": "Dagenham"},
    {"league": "England League Two", "team": "Exeter City"},
    {"league": "England League Two", "team": "Fleetwood Town"},
    {"league": "England League Two", "team": "Hartlepool"},
    {"league": "England League Two", "team": "Mansfield Town"},
    {"league": "England League Two", "team": "Morecambe"},
    {"league": "England League Two", "team": "Newport County"},
    {"league": "England League Two", "team": "Northampton"},
    {"league": "England League Two", "team": "Oxford United"},
    {"league": "England League Two", "team": "Plymouth Argyle"},
    {"league": "England League Two", "team": "Portsmouth"},
    {"league": "England League Two", "team": "Rochdale"},
    {"league": "England League Two", "team": "Scunthorpe Utd"},
    {"league": "England League Two", "team": "Southend United"},
    {"league": "England League Two", "team": "Torquay United"},
    {"league": "England League Two", "team": "Wycombe"},
    {"league": "England League Two", "team": "York City"},
    //France Ligue 1
    {"league": "France Ligue 1", "team": "AC Ajaccio"},
    {"league": "France Ligue 1", "team": "AS Monaco"},
    {"league": "France Ligue 1", "team": "Bordeaux"},
    {"league": "France Ligue 1", "team": "EA Guingamp"},
    {"league": "France Ligue 1", "team": "Evian Thonon FC"},
    {"league": "France Ligue 1", "team": "FC Lorient"},
    {"league": "France Ligue 1", "team": "FC Nantes"},
    {"league": "France Ligue 1", "team": "FC Sochaux"},
    {"league": "France Ligue 1", "team": "LOSC Lille"},
    {"league": "France Ligue 1", "team": "Marseille"},
    {"league": "France Ligue 1", "team": "Montpellier HSC"},
    {"league": "France Ligue 1", "team": "OGC Nice"},
    {"league": "France Ligue 1", "team": "Olympique Lyon"},
    {"league": "France Ligue 1", "team": "PSG"},
    {"league": "France Ligue 1", "team": "Saint-Etienne"},
    {"league": "France Ligue 1", "team": "SC Bastia"},
    {"league": "France Ligue 1", "team": "Stade Reims"},
    {"league": "France Ligue 1", "team": "Stade Rennais"},
    {"league": "France Ligue 1", "team": "Toulouse FC"},
    {"league": "France Ligue 1", "team": "Valenciennes FC"},
    //France Ligue 2
    {"league": "France Ligue 2", "team": "AC Arles"},
    {"league": "France Ligue 2", "team": "AJ Auxerre"},
    {"league": "France Ligue 2", "team": "Angers SCO"},
    {"league": "France Ligue 2", "team": "AS Nancy"},
    {"league": "France Ligue 2", "team": "CA Bastia"},
    {"league": "France Ligue 2", "team": "Cham. Niortais"},
    {"league": "France Ligue 2", "team": "Clermont Foot"},
    {"league": "France Ligue 2", "team": "Dijon FCO"},
    {"league": "France Ligue 2", "team": "ES Troyes"},
    {"league": "France Ligue 2", "team": "FC Istres"},
    {"league": "France Ligue 2", "team": "FC Metz"},
    {"league": "France Ligue 2", "team": "LB Chateauroux"},
    {"league": "France Ligue 2", "team": "Le Havre AC"},
    {"league": "France Ligue 2", "team": "Nîmes Olympique"},
    {"league": "France Ligue 2", "team": "RC Lens"},
    {"league": "France Ligue 2", "team": "SM Caen"},
    {"league": "France Ligue 2", "team": "Stade Brest"},
    {"league": "France Ligue 2", "team": "Stade Lavallois"},
    {"league": "France Ligue 2", "team": "Tours FC"},
    {"league": "France Ligue 2", "team": "US Créteil"},
    //Germany 1. Bundesliga
    {"league": "Germany 1. Bundesliga", "team": "FC Nuremberg"},
    {"league": "Germany 1. Bundesliga", "team": "FSV Mainz 05"},
    {"league": "Germany 1. Bundesliga", "team": "1899 Hoffenheim"},
    {"league": "Germany 1. Bundesliga", "team": "Bayer 04"},
    {"league": "Germany 1. Bundesliga", "team": "Bor. Dortmund"},
    {"league": "Germany 1. Bundesliga", "team": "Bor. M'gladbach"},
    {"league": "Germany 1. Bundesliga", "team": "Braunschweig"},
    {"league": "Germany 1. Bundesliga", "team": "Eint. Frankfurt"},
    {"league": "Germany 1. Bundesliga", "team": "FC Augsburg"},
    {"league": "Germany 1. Bundesliga", "team": "FC Bayern"},
    {"league": "Germany 1. Bundesliga", "team": "FC Schalke 04"},
    {"league": "Germany 1. Bundesliga", "team": "Hamburger SV"},
    {"league": "Germany 1. Bundesliga", "team": "Hannover 96"},
    {"league": "Germany 1. Bundesliga", "team": "Hertha BSC"},
    {"league": "Germany 1. Bundesliga", "team": "SC Freiburg"},
    {"league": "Germany 1. Bundesliga", "team": "VfB Stuttgart"},
    {"league": "Germany 1. Bundesliga", "team": "VfL Wolfsburg"},
    {"league": "Germany 1. Bundesliga", "team": "Werder Bremen"},
    //Germany 2. Bundesliga
    {"league": "Germany 2. Bundesliga", "team": "FC K'lautern"},
    {"league": "Germany 2. Bundesliga", "team": "FC Köln"},
    {"league": "Germany 2. Bundesliga", "team": "1860 Munich"},
    {"league": "Germany 2. Bundesliga", "team": "Arm. Bielefeld"},
    {"league": "Germany 2. Bundesliga", "team": "Dynamo Dresden"},
    {"league": "Germany 2. Bundesliga", "team": "Energie Cottbus"},
    {"league": "Germany 2. Bundesliga", "team": "Erzgebirge Aue"},
    {"league": "Germany 2. Bundesliga", "team": "F. Düsseldorf"},
    {"league": "Germany 2. Bundesliga", "team": "FC Ingolstadt"},
    {"league": "Germany 2. Bundesliga", "team": "FC St. Pauli"},
    {"league": "Germany 2. Bundesliga", "team": "FSV Frankfurt"},
    {"league": "Germany 2. Bundesliga", "team": "Greuther Fürth"},
    {"league": "Germany 2. Bundesliga", "team": "Karlsruher SC"},
    {"league": "Germany 2. Bundesliga", "team": "SC Paderborn"},
    {"league": "Germany 2. Bundesliga", "team": "SV Sandhausen"},
    {"league": "Germany 2. Bundesliga", "team": "Union Berlin"},
    {"league": "Germany 2. Bundesliga", "team": "VfL Bochum"},
    {"league": "Germany 2. Bundesliga", "team": "VfR Aalen"},
    //Holland Eredivisie
    {"league": "Holland Eredivisie", "team": "ADO Den Haag"},
    {"league": "Holland Eredivisie", "team": "Ajax"},
    {"league": "Holland Eredivisie", "team": "AZ"},
    {"league": "Holland Eredivisie", "team": "FC Groningen"},
    {"league": "Holland Eredivisie", "team": "FC Twente"},
    {"league": "Holland Eredivisie", "team": "FC Utrecht"},
    {"league": "Holland Eredivisie", "team": "Feyenoord"},
    {"league": "Holland Eredivisie", "team": "Go Ahead Eagles"},
    {"league": "Holland Eredivisie", "team": "Heracles Almelo"},
    {"league": "Holland Eredivisie", "team": "N.E.C."},
    {"league": "Holland Eredivisie", "team": "NAC Breda"},
    {"league": "Holland Eredivisie", "team": "PEC Zwolle"},
    {"league": "Holland Eredivisie", "team": "PSV"},
    {"league": "Holland Eredivisie", "team": "RKC Waalwijk"},
    {"league": "Holland Eredivisie", "team": "Roda JC"},
    {"league": "Holland Eredivisie", "team": "SC Cambuur"},
    {"league": "Holland Eredivisie", "team": "sc Heerenveen"},
    {"league": "Holland Eredivisie", "team": "Vitesse"},
    //Italy Serie A
    {"league": "Italy Serie A", "team": "Atalanta"},
    {"league": "Italy Serie A", "team": "Bologna"},
    {"league": "Italy Serie A", "team": "Cagliari"},
    {"league": "Italy Serie A", "team": "Catania"},
    {"league": "Italy Serie A", "team": "Chievo Verona"},
    {"league": "Italy Serie A", "team": "Fiorentina"},
    {"league": "Italy Serie A", "team": "Genoa"},
    {"league": "Italy Serie A", "team": "Hellas Verona"},
    {"league": "Italy Serie A", "team": "Inter"},
    {"league": "Italy Serie A", "team": "Juventus"},
    {"league": "Italy Serie A", "team": "Lazio"},
    {"league": "Italy Serie A", "team": "Livorno"},
    {"league": "Italy Serie A", "team": "Milan"},
    {"league": "Italy Serie A", "team": "Napoli"},
    {"league": "Italy Serie A", "team": "Parma"},
    {"league": "Italy Serie A", "team": "Roma"},
    {"league": "Italy Serie A", "team": "Sampdoria"},
    {"league": "Italy Serie A", "team": "Sassuolo"},
    {"league": "Italy Serie A", "team": "Torino"},
    {"league": "Italy Serie A", "team": "Udinese"},
    //Italy Serie B
    {"league": "Italy Serie B", "team": "Brescia"},
    {"league": "Italy Serie B", "team": "Avellino"},
    {"league": "Italy Serie B", "team": "Bari"},
    {"league": "Italy Serie B", "team": "C. Stabia"},
    {"league": "Italy Serie B", "team": "Carpi"},
    {"league": "Italy Serie B", "team": "Cesena"},
    {"league": "Italy Serie B", "team": "Cittadella"},
    {"league": "Italy Serie B", "team": "Crotone"},
    {"league": "Italy Serie B", "team": "Empoli"},
    {"league": "Italy Serie B", "team": "La Spezia"},
    {"league": "Italy Serie B", "team": "Lanciano"},
    {"league": "Italy Serie B", "team": "Latina"},
    {"league": "Italy Serie B", "team": "Modena"},
    {"league": "Italy Serie B", "team": "Novara"},
    {"league": "Italy Serie B", "team": "Padua"},
    {"league": "Italy Serie B", "team": "Palermo"},
    {"league": "Italy Serie B", "team": "Pescara"},
    {"league": "Italy Serie B", "team": "Reggio Calabria"},
    {"league": "Italy Serie B", "team": "Siena"},
    {"league": "Italy Serie B", "team": "Terni"},
    {"league": "Italy Serie B", "team": "Trapani"},
    {"league": "Italy Serie B", "team": "Varese"},
    //Norway Tippeligaen
    {"league": "Norway Tippeligaen", "team": "Aalesunds FK"},
    {"league": "Norway Tippeligaen", "team": "FK Haugesund"},
    {"league": "Norway Tippeligaen", "team": "Hønefoss BK"},
    {"league": "Norway Tippeligaen", "team": "Lillestrøm SK"},
    {"league": "Norway Tippeligaen", "team": "Molde FK"},
    {"league": "Norway Tippeligaen", "team": "ODD"},
    {"league": "Norway Tippeligaen", "team": "Rosenborg BK"},
    {"league": "Norway Tippeligaen", "team": "Sandnes Ulf"},
    {"league": "Norway Tippeligaen", "team": "Sarpsborg"},
    {"league": "Norway Tippeligaen", "team": "SK Brann"},
    {"league": "Norway Tippeligaen", "team": "Sogndal"},
    {"league": "Norway Tippeligaen", "team": "Start"},
    {"league": "Norway Tippeligaen", "team": "Strømsgodset IF"},
    {"league": "Norway Tippeligaen", "team": "Tromsø IL"},
    {"league": "Norway Tippeligaen", "team": "Vålerenga"},
    {"league": "Norway Tippeligaen", "team": "Viking FK"},
    //Poland T-Mobile Ekstraklasa
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Cracovia Kraków"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Górnik Zabrze"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Jag. Białystok"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Korona Kielce"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Lech Poznań"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Lechia Gdańsk"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Legia Warszawa"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Piast Gliwice"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Podbeskidzie"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Pogoń Szczecin"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Ruch Chorzów"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Śląsk Wrocław"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Widzew Łódź"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Wisła Kraków"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Zagłębie Lubin"},
    {"league": "Poland T-Mobile Ekstraklasa", "team": "Zaw. Bydgoszcz"},
    //Portugal Liga ZON SAGRES
    {"league": "Portugal Liga ZON SAGRES", "team": "Académica"},
    {"league": "Portugal Liga ZON SAGRES", "team": "Belenenses (Belém)"},
    {"league": "Portugal Liga ZON SAGRES", "team": "CD Nacional"},
    {"league": "Portugal Liga ZON SAGRES", "team": "CS Marítimo(C. Funchal)"},
    {"league": "Portugal Liga ZON SAGRES", "team": "Estoril-Praia (Estoril)"},
    {"league": "Portugal Liga ZON SAGRES", "team": "FC Arouca (Arouca)"},
    {"league": "Portugal Liga ZON SAGRES", "team": "FC Porto"},
    {"league": "Portugal Liga ZON SAGRES", "team": "Gil-Vicente (V. Barcelos)"},
    {"league": "Portugal Liga ZON SAGRES", "team": "Paços Ferreira"},
    {"league": "Portugal Liga ZON SAGRES", "team": "Rio Ave FC"},
    {"league": "Portugal Liga ZON SAGRES", "team": "S.C. Olhanense"},
    {"league": "Portugal Liga ZON SAGRES", "team": "SC Braga"},
    {"league": "Portugal Liga ZON SAGRES", "team": "SL Benfica"},
    {"league": "Portugal Liga ZON SAGRES", "team": "Sporting CP"},
    {"league": "Portugal Liga ZON SAGRES", "team": "Vit. Guimarães"},
    {"league": "Portugal Liga ZON SAGRES", "team": "Vitória FC"},
    //Rep. Ireland Airtricity League
    {"league": "Rep. Ireland Airtricity League", "team": "Bohemians FC"},
    {"league": "Rep. Ireland Airtricity League", "team": "Bray Wanderers"},
    {"league": "Rep. Ireland Airtricity League", "team": "Cork City"},
    {"league": "Rep. Ireland Airtricity League", "team": "Derry City"},
    {"league": "Rep. Ireland Airtricity League", "team": "Drogheda Utd"},
    {"league": "Rep. Ireland Airtricity League", "team": "Dundalk"},
    {"league": "Rep. Ireland Airtricity League", "team": "Limerick"},
    {"league": "Rep. Ireland Airtricity League", "team": "Shamrock Rovers"},
    {"league": "Rep. Ireland Airtricity League", "team": "Shelbourne"},
    {"league": "Rep. Ireland Airtricity League", "team": "Sligo Rovers"},
    {"league": "Rep. Ireland Airtricity League", "team": "St. Pats"},
    {"league": "Rep. Ireland Airtricity League", "team": "UCD AFC"},
    //Russia Premier League
    {"league": "Russia Premier League", "team": "Makhachkala"},
    {"league": "Russia Premier League", "team": "Amkar Perm"},
    {"league": "Russia Premier League", "team": "CSKA Moskva"},
    {"league": "Russia Premier League", "team": "Dinamo Moskva"},
    {"league": "Russia Premier League", "team": "FC Krasnodar"},
    {"league": "Russia Premier League", "team": "FC Rostov"},
    {"league": "Russia Premier League", "team": "FC Tom Tomsk"},
    {"league": "Russia Premier League", "team": "FC Ural"},
    {"league": "Russia Premier League", "team": "Krylya Sovetov"},
    {"league": "Russia Premier League", "team": "Kuban Krasnodar"},
    {"league": "Russia Premier League", "team": "Lokomotiv"},
    {"league": "Russia Premier League", "team": "Rubin Kazan"},
    {"league": "Russia Premier League", "team": "Spartak Moskva"},
    {"league": "Russia Premier League", "team": "Terek Grozny"},
    {"league": "Russia Premier League", "team": "Volga"},
    {"league": "Russia Premier League", "team": "Zenit"},
    //Scotland Premier League
    {"league": "Scotland Premier League", "team": "Aberdeen"},
    {"league": "Scotland Premier League", "team": "Celtic"},
    {"league": "Scotland Premier League", "team": "Dundee United"},
    {"league": "Scotland Premier League", "team": "Hearts"},
    {"league": "Scotland Premier League", "team": "Hibernian"},
    {"league": "Scotland Premier League", "team": "Inverness CT"},
    {"league": "Scotland Premier League", "team": "Kilmarnock"},
    {"league": "Scotland Premier League", "team": "Motherwell"},
    {"league": "Scotland Premier League", "team": "Partick Thistle"},
    {"league": "Scotland Premier League", "team": "Ross County"},
    {"league": "Scotland Premier League", "team": "St. Johnstone"},
    {"league": "Scotland Premier League", "team": "St. Mirren"},
    //Spain Primera Division
    {"league": "Spain Primera Division", "team": "Athletic Bilbao"},
    {"league": "Spain Primera Division", "team": "Atlético Madrid"},
    {"league": "Spain Primera Division", "team": "CA Osasuna"},
    {"league": "Spain Primera Division", "team": "Celta Vigo"},
    {"league": "Spain Primera Division", "team": "Elche CF"},
    {"league": "Spain Primera Division", "team": "FC Barcelona"},
    {"league": "Spain Primera Division", "team": "Getafe CF"},
    {"league": "Spain Primera Division", "team": "Granada CF"},
    {"league": "Spain Primera Division", "team": "Levante UD"},
    {"league": "Spain Primera Division", "team": "Málaga CF"},
    {"league": "Spain Primera Division", "team": "Rayo Vallecano"},
    {"league": "Spain Primera Division", "team": "RCD Espanyol"},
    {"league": "Spain Primera Division", "team": "Real Betis"},
    {"league": "Spain Primera Division", "team": "Real Madrid"},
    {"league": "Spain Primera Division", "team": "Real Sociedad"},
    {"league": "Spain Primera Division", "team": "Real Valladolid"},
    {"league": "Spain Primera Division", "team": "Sevilla FC"},
    {"league": "Spain Primera Division", "team": "UD Almería"},
    {"league": "Spain Primera Division", "team": "Valencia CF"},
    {"league": "Spain Primera Division", "team": "Villarreal CF"},
    //Spain Segunda A
    {"league": "Spain Segunda A", "team": "AD Alcorcón"},
    {"league": "Spain Segunda A", "team": "CD Lugo"},
    {"league": "Spain Segunda A", "team": "CD Mirandés"},
    {"league": "Spain Segunda A", "team": "CD Numancia"},
    {"league": "Spain Segunda A", "team": "CD Tenerife"},
    {"league": "Spain Segunda A", "team": "Córdoba CF"},
    {"league": "Spain Segunda A", "team": "Deport. Alavés"},
    {"league": "Spain Segunda A", "team": "FC Barcelona B"},
    {"league": "Spain Segunda A", "team": "Girona CF"},
    {"league": "Spain Segunda A", "team": "Hércules CF"},
    {"league": "Spain Segunda A", "team": "RC Deportivo"},
    {"league": "Spain Segunda A", "team": "RC Recreativo"},
    {"league": "Spain Segunda A", "team": "RCD Mallorca"},
    {"league": "Spain Segunda A", "team": "Real Jaén CF"},
    {"league": "Spain Segunda A", "team": "Real Murcia CF"},
    {"league": "Spain Segunda A", "team": "Real Zaragoza"},
    {"league": "Spain Segunda A", "team": "RM Castilla"},
    {"league": "Spain Segunda A", "team": "Sabadell FC"},
    {"league": "Spain Segunda A", "team": "SD Eibar"},
    {"league": "Spain Segunda A", "team": "SD Ponferradina"},
    {"league": "Spain Segunda A", "team": "Sporting Gijón"},
    {"league": "Spain Segunda A", "team": "UD Las Palmas"},
    //Sweden Allsvenskan
    {"league": "Sweden Allsvenskan", "team": "AIK Fotboll"},
    {"league": "Sweden Allsvenskan", "team": "Åtvidabergs FF "},
    {"league": "Sweden Allsvenskan", "team": "BK Häcken"},
    {"league": "Sweden Allsvenskan", "team": "Brommapojkarna"},
    {"league": "Sweden Allsvenskan", "team": "Djurgårdens IF"},
    {"league": "Sweden Allsvenskan", "team": "Gefle IF"},
    {"league": "Sweden Allsvenskan", "team": "Halmstads BK"},
    {"league": "Sweden Allsvenskan", "team": "Helsingborgs IF"},
    {"league": "Sweden Allsvenskan", "team": "IF Elfsborg"},
    {"league": "Sweden Allsvenskan", "team": "IFK Göteborg"},
    {"league": "Sweden Allsvenskan", "team": "IFK Norrköping"},
    {"league": "Sweden Allsvenskan", "team": "Kalmar FF"},
    {"league": "Sweden Allsvenskan", "team": "Malmö FF"},
    {"league": "Sweden Allsvenskan", "team": "Mjällby AIF"},
    {"league": "Sweden Allsvenskan", "team": "Östers IF"},
    {"league": "Sweden Allsvenskan", "team": "Syrianska"},
    //Switzerland Super League
    {"league": "Switzerland Super League", "team": "BSC Young BoysF"},
    {"league": "Switzerland Super League", "team": "FC Aarau"},
    {"league": "Switzerland Super League", "team": "FC Basel"},
    {"league": "Switzerland Super League", "team": "FC Lausanne"},
    {"league": "Switzerland Super League", "team": "FC Luzern"},
    {"league": "Switzerland Super League", "team": "FC Sion"},
    {"league": "Switzerland Super League", "team": "FC St. Gallen"},
    {"league": "Switzerland Super League", "team": "FC Thun"},
    {"league": "Switzerland Super League", "team": "FC Zürich"},
    {"league": "Switzerland Super League", "team": "Grasshopper"},
    //Hyundai A-League
    {"league": "Hyundai A-League", "team": "Adelaide United"},
    {"league": "Hyundai A-League", "team": "Brisbane Roar"},
    {"league": "Hyundai A-League", "team": "Central Coast"},
    {"league": "Hyundai A-League", "team": "Melb. Victory"},
    {"league": "Hyundai A-League", "team": "Melbourne Heart"},
    {"league": "Hyundai A-League", "team": "Newcastle Jets"},
    {"league": "Hyundai A-League", "team": "Perth Glory"},
    {"league": "Hyundai A-League", "team": "Sydney FC"},
    {"league": "Hyundai A-League", "team": "Wanderers FC"},
    {"league": "Hyundai A-League", "team": "Well. Phoenix"},
    //Korea K League Classic
    {"league": "Korea K League Classic", "team": "Busan I'Park"},
    {"league": "Korea K League Classic", "team": "Chunnam Dragons"},
    {"league": "Korea K League Classic", "team": "Daegu FC"},
    {"league": "Korea K League Classic", "team": "Daejeon Citizen"},
    {"league": "Korea K League Classic", "team": "FC Seoul"},
    {"league": "Korea K League Classic", "team": "Gangwon FC"},
    {"league": "Korea K League Classic", "team": "GyeongNam FC"},
    {"league": "Korea K League Classic", "team": "Incheon United"},
    {"league": "Korea K League Classic", "team": "Jeju United FC"},
    {"league": "Korea K League Classic", "team": "Jeonbuk FC"},
    {"league": "Korea K League Classic", "team": "Pohang Steelers"},
    {"league": "Korea K League Classic", "team": "Seongnam Ilhwa"},
    {"league": "Korea K League Classic", "team": "Suwon Bluewings"},
    {"league": "Korea K League Classic", "team": "Ulsan Hyundai"},
    //Saudi Abdul Latif Jameel League
    {"league": "Saudi Abdul Latif Jameel League", "team": "Al-Ahli"},
    {"league": "Saudi Abdul Latif Jameel League", "team": "Al-Ettifaq"},
    {"league": "Saudi Abdul Latif Jameel League", "team": "Al-Faisaly"},
    {"league": "Saudi Abdul Latif Jameel League", "team": "Al-Fateh"},
    {"league": "Saudi Abdul Latif Jameel League", "team": "Al-Hilal"},
    {"league": "Saudi Abdul Latif Jameel League", "team": "Al-Ittihad"},
    {"league": "Saudi Abdul Latif Jameel League", "team": "Al-Nahdha"},
    {"league": "Saudi Abdul Latif Jameel League", "team": "Al-Nassr"},
    {"league": "Saudi Abdul Latif Jameel League", "team": "Al-Orubah FC"},
    {"league": "Saudi Abdul Latif Jameel League", "team": "Al-Raed"},
    {"league": "Saudi Abdul Latif Jameel League", "team": "Al-Shabab"},
    {"league": "Saudi Abdul Latif Jameel League", "team": "Alshoulla"},
    {"league": "Saudi Abdul Latif Jameel League", "team": "Al-Taawoun"},
    {"league": "Saudi Abdul Latif Jameel League", "team": "Najran"},
    //International
    {"league": "International", "team": "Argentina"},
    {"league": "International", "team": "Australia"},
    {"league": "International", "team": "Austria"},
    {"league": "International", "team": "Belgium"},
    {"league": "International", "team": "Bolivia"},
    {"league": "International", "team": "Brazil"},
    {"league": "International", "team": "Bulgaria"},
    {"league": "International", "team": "Cameroon"},
    {"league": "International", "team": "Chile"},
    {"league": "International", "team": "Colombia"},
    {"league": "International", "team": "Côte d'Ivoire"},
    {"league": "International", "team": "Czech Republic"},
    {"league": "International", "team": "Denmark"},
    {"league": "International", "team": "Ecuador"},
    {"league": "International", "team": "Egypt"},
    {"league": "International", "team": "England"},
    {"league": "International", "team": "Finland"},
    {"league": "International", "team": "France"},
    {"league": "International", "team": "Germany"},
    {"league": "International", "team": "Greece"},
    {"league": "International", "team": "Hungary"},
    {"league": "International", "team": "India"},
    {"league": "International", "team": "Ireland"},
    {"league": "International", "team": "Italy"},
    {"league": "International", "team": "Korea Republic"},
    {"league": "International", "team": "Mexico"},
    {"league": "International", "team": "Netherlands"},
    {"league": "International", "team": "New Zealand"},
    {"league": "International", "team": "Northern Ireland"},
    {"league": "International", "team": "Norway"},
    {"league": "International", "team": "Paraguay"},
    {"league": "International", "team": "Peru"},
    {"league": "International", "team": "Poland"},
    {"league": "International", "team": "Portugal"},
    {"league": "International", "team": "Romania"},
    {"league": "International", "team": "Russia"},
    {"league": "International", "team": "Scotland"},
    {"league": "International", "team": "Slovenia"},
    {"league": "International", "team": "South Africa"},
    {"league": "International", "team": "Spain"},
    {"league": "International", "team": "Sweden"},
    {"league": "International", "team": "Switzerland"},
    {"league": "International", "team": "Turkey"},
    {"league": "International", "team": "United States"},
    {"league": "International", "team": "Uruguay"},
    {"league": "International", "team": "Venezuela"},
    {"league": "International", "team": "Wales"},
    //Rest of World
    {"league": "Rest of World", "team": "adidas All-Star"},
    {"league": "Rest of World", "team": "AEK Athens"},
    {"league": "Rest of World", "team": "Classic XI"},
    {"league": "Rest of World", "team": "FC Shakhtar"},
    {"league": "Rest of World", "team": "Galatasaray SK"},
    {"league": "Rest of World", "team": "Independiente"},
    {"league": "Rest of World", "team": "Kaizer Chiefs"},
    {"league": "Rest of World", "team": "MLS All Stars"},
    {"league": "Rest of World", "team": "Olympiakos CFP"},
    {"league": "Rest of World", "team": "Orlando Pirates"},
    {"league": "Rest of World", "team": "Palmeiras"},
    {"league": "Rest of World", "team": "Panathinaikos"},
    {"league": "Rest of World", "team": "PAOK"},
    {"league": "Rest of World", "team": "Rangers"},
    {"league": "Rest of World", "team": "World XI"}];